################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_acmp.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cmu.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_core.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_dma.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_ebi.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_emu.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpio.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lcd.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lesense.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_msc.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rtc.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_system.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_usart.c \
C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_vcmp.c 

OBJS += \
./gecko_sdk_4.4.6/platform/emlib/src/em_acmp.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_core.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_dma.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_ebi.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_emu.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_lcd.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_lesense.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_msc.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_rtc.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_system.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_usart.o \
./gecko_sdk_4.4.6/platform/emlib/src/em_vcmp.o 

C_DEPS += \
./gecko_sdk_4.4.6/platform/emlib/src/em_acmp.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_core.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_dma.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_ebi.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_emu.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_lcd.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_lesense.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_msc.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_rtc.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_system.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_usart.d \
./gecko_sdk_4.4.6/platform/emlib/src/em_vcmp.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.4.6/platform/emlib/src/em_acmp.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_acmp.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_acmp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_cmu.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cmu.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_core.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_core.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_dma.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_dma.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_dma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_ebi.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_ebi.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_ebi.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_emu.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_emu.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_gpio.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpio.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_lcd.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lcd.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_lcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_lesense.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lesense.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_lesense.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_msc.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_msc.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_rtc.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rtc.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_rtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_system.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_system.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_usart.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_usart.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.6/platform/emlib/src/em_vcmp.o: C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_vcmp.c gecko_sdk_4.4.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32GG990F1024=1' '-DHFXO_FREQ=48000000' '-DSL_BOARD_NAME="BRD2200A"' '-DSL_BOARD_REV="B05"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\config" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat\autogen" -I"C:\Users\smarc\SimplicityStudio\v5_workspace\BSzF_hazi_feladat" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/smarc/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.6/platform/emlib/src/em_vcmp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


